import { existsSync, readFileSync } from 'node:fs';
import { hostname } from 'node:os';
import { configPath, gbrainPath } from '../config.ts';
import {
  queueZeroPaidSpendEnabled,
  queueZeroPaidSpendValueIsAmbiguous,
} from './zero-paid-spend-policy.ts';

export type ZeroPaidSpendFileState = 'on' | 'off' | 'unset' | 'missing' | 'invalid' | 'unreadable';
export type ZeroPaidSpendWrapperDeclaration = 'declares_on' | 'declares_off' | 'noncanonical' | 'missing' | 'unreadable';

export interface ZeroPaidSpendStatus {
  current_process: 'on' | 'off';
  current_process_value_ambiguous: boolean;
  durable_autopilot: ZeroPaidSpendFileState;
  wrapper_declaration: ZeroPaidSpendWrapperDeclaration;
  configuration_consistent: boolean;
}

export interface SupervisorZeroPaidSpendStatus extends ZeroPaidSpendStatus {
  live_supervisor: boolean | null;
}

interface StatusPaths {
  configFile?: string;
  wrapperFile?: string;
}

const WRAPPER_MARKER = '# Queue workers may call only explicitly local inference providers.';
const WRAPPER_HEADER = '#!/bin/bash\n# Auto-generated by gbrain autopilot --install\n';

function wrapperHasTopLevelExport(source: string): boolean {
  if (!source.startsWith(WRAPPER_HEADER)) return false;
  const marker = `\n${WRAPPER_MARKER}\nexport GBRAIN_QUEUE_ZERO_PAID_SPEND=1\n`;
  const markerIndex = source.indexOf(marker);
  if (markerIndex < 0) return false;
  const executable = source.slice(0, markerIndex).split(/\r?\n/)
    .map(line => line.trim()).filter(line => line && !line.startsWith('#'));
  if (executable.length !== 5) return false;
  if (executable[0] !== '[ -f ~/.zshenv ] && source ~/.zshenv 2>/dev/null') return false;
  if (executable[1] !== '[ -f ~/.zshrc ] && source ~/.zshrc 2>/dev/null') return false;
  if (executable[2] !== '[ -f ~/.bashrc ] && source ~/.bashrc 2>/dev/null') return false;
  if (!/^\[ -f '([^']+)' \] && \{ set -a; source '\1' 2>\/dev\/null; set \+a; \}$/.test(executable[3])) return false;
  return /^export PATH=(?:'[^']+':)?"\$HOME\/\.bun\/bin:\$PATH"$/.test(executable[4]);
}

/**
 * Read-only operator snapshot. This reports evidence; it never enforces.
 * `assertZeroPaidSpendAdmission` inside invokeAI remains the sole admission gate.
 */
export function inspectZeroPaidSpendStatus(
  env: NodeJS.ProcessEnv = process.env,
  paths: StatusPaths = {},
): ZeroPaidSpendStatus {
  const configFile = paths.configFile ?? configPath();
  const wrapperFile = paths.wrapperFile ?? gbrainPath('autopilot-run.sh');

  let durable: ZeroPaidSpendFileState = 'missing';
  if (existsSync(configFile)) {
    try {
      const parsed = JSON.parse(readFileSync(configFile, 'utf8')) as unknown;
      if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
        durable = 'invalid';
      } else {
        const autopilot = (parsed as { autopilot?: unknown }).autopilot;
        if (autopilot === undefined) {
          durable = 'unset';
        } else if (autopilot === null || typeof autopilot !== 'object' || Array.isArray(autopilot)) {
          durable = 'invalid';
        } else if (!Object.prototype.hasOwnProperty.call(autopilot, 'zero_paid_spend')) {
          durable = 'unset';
        } else {
          const value = (autopilot as { zero_paid_spend?: unknown }).zero_paid_spend;
          durable = value === true ? 'on' : value === false ? 'off' : 'invalid';
        }
      }
    } catch {
      durable = 'unreadable';
    }
  }

  let wrapper: ZeroPaidSpendWrapperDeclaration = 'missing';
  if (existsSync(wrapperFile)) {
    try {
      const source = readFileSync(wrapperFile, 'utf8');
      wrapper = wrapperHasTopLevelExport(source)
        ? 'declares_on'
        : source.startsWith(WRAPPER_HEADER) && !source.includes('GBRAIN_QUEUE_ZERO_PAID_SPEND')
          ? 'declares_off'
          : 'noncanonical';
    } catch {
      wrapper = 'unreadable';
    }
  }

  const configurationConsistent = durable === 'on'
    ? wrapper === 'declares_on'
    : (durable === 'off' || durable === 'unset' || durable === 'missing')
      ? wrapper === 'declares_off' || wrapper === 'missing'
      : false;

  return {
    current_process: queueZeroPaidSpendEnabled(env) ? 'on' : 'off',
    current_process_value_ambiguous: queueZeroPaidSpendValueIsAmbiguous(env),
    durable_autopilot: durable,
    wrapper_declaration: wrapper,
    configuration_consistent: configurationConsistent,
  };
}

export function supervisorZeroPaidSpendStatus(
  events: ReadonlyArray<Record<string, unknown>>,
  liveIdentity: { holder_pid: number; holder_host: string; acquisition_token: string } | null,
  queue: string,
): SupervisorZeroPaidSpendStatus {
  const liveLocalPid = liveIdentity?.holder_host === hostname() ? liveIdentity.holder_pid : null;
  const startedEvent = liveLocalPid === null ? null : [...events].reverse().find(event =>
    event.event === 'started' &&
    event.supervisor_pid === liveLocalPid &&
    event.queue === queue &&
    event.lock_acquisition_token === liveIdentity?.acquisition_token,
  ) ?? null;
  return {
    live_supervisor: typeof startedEvent?.zero_paid_spend === 'boolean'
      ? startedEvent.zero_paid_spend
      : null,
    ...inspectZeroPaidSpendStatus(),
  };
}

export function formatSupervisorZeroPaidSpendStatus(status: SupervisorZeroPaidSpendStatus): string {
  return `  Zero paid spend: live=${status.live_supervisor === null ? 'unknown' : status.live_supervisor ? 'on' : 'off'} ` +
    `durable=${status.durable_autopilot} wrapper=${status.wrapper_declaration} ` +
    `status=${status.configuration_consistent ? 'configured' : 'mismatch'}`;
}

export function buildZeroPaidSpendDoctorCheck(name: 'queue_zero_paid_spend' = 'queue_zero_paid_spend'): {
  name: 'queue_zero_paid_spend';
  status: 'ok' | 'warn';
  message: string;
  details: Record<string, unknown>;
} {
  const status = inspectZeroPaidSpendStatus();
  const needsAttention = !status.configuration_consistent || status.current_process_value_ambiguous;
  return {
    name,
    status: needsAttention ? 'warn' : 'ok',
    message:
      `current_process=${status.current_process}` +
      `${status.current_process_value_ambiguous ? ' (unrecognized value; enforced fail-closed)' : ''} ` +
      `durable_autopilot=${status.durable_autopilot} wrapper_declaration=${status.wrapper_declaration} ` +
      (status.configuration_consistent
        ? '(configuration declarations agree; only current_process or `gbrain jobs supervisor status` is enforcement evidence)'
        : '(configuration mismatch or unreadable state; re-run `gbrain autopilot --install`)'),
    details: { ...status },
  };
}
