import { afterEach, describe, expect, test } from 'bun:test';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { hostname, tmpdir } from 'node:os';
import {
  buildZeroPaidSpendDoctorCheck,
  formatSupervisorZeroPaidSpendStatus,
  inspectZeroPaidSpendStatus,
  supervisorZeroPaidSpendStatus,
} from '../../src/core/ai/zero-paid-spend-status.ts';
import { withEnv } from '../helpers/with-env.ts';

const roots: string[] = [];

function generatedWrapper(beforeMarker = '', afterExport = ''): string {
  return '#!/bin/bash\n# Auto-generated by gbrain autopilot --install\n' +
    '[ -f ~/.zshenv ] && source ~/.zshenv 2>/dev/null\n' +
    '[ -f ~/.zshrc ] && source ~/.zshrc 2>/dev/null\n' +
    '[ -f ~/.bashrc ] && source ~/.bashrc 2>/dev/null\n' +
    "[ -f '/tmp/gbrain-env' ] && { set -a; source '/tmp/gbrain-env' 2>/dev/null; set +a; }\n" +
    'export PATH="$HOME/.bun/bin:$PATH"\n' + beforeMarker +
    '# Queue workers may call only explicitly local inference providers.\n' +
    'export GBRAIN_QUEUE_ZERO_PAID_SPEND=1\n' + afterExport;
}

function fixture(): { root: string; configFile: string; wrapperFile: string } {
  const root = mkdtempSync(join(tmpdir(), 'gbrain-zero-spend-status-'));
  roots.push(root);
  return {
    root,
    configFile: join(root, 'config.json'),
    wrapperFile: join(root, 'autopilot-run.sh'),
  };
}

afterEach(() => {
  while (roots.length > 0) rmSync(roots.pop()!, { recursive: true, force: true });
});

describe('inspectZeroPaidSpendStatus', () => {
  test('reports consistent durable and wrapper declarations separately from this process', () => {
    const paths = fixture();
    writeFileSync(paths.configFile, JSON.stringify({ autopilot: { zero_paid_spend: true } }));
    writeFileSync(paths.wrapperFile, generatedWrapper());

    expect(inspectZeroPaidSpendStatus({}, paths)).toEqual({
      current_process: 'off',
      current_process_value_ambiguous: false,
      durable_autopilot: 'on',
      wrapper_declaration: 'declares_on',
      configuration_consistent: true,
    });
  });

  test('flags a noncanonical stale wrapper after the durable choice is on', () => {
    const paths = fixture();
    writeFileSync(paths.configFile, JSON.stringify({ autopilot: { zero_paid_spend: true } }));
    writeFileSync(paths.wrapperFile, '#!/bin/bash\nexec gbrain autopilot\n');

    const status = inspectZeroPaidSpendStatus({}, paths);
    expect(status.durable_autopilot).toBe('on');
    expect(status.wrapper_declaration).toBe('noncanonical');
    expect(status.configuration_consistent).toBe(false);
  });

  test('does not mistake an export hidden in a false branch for active wrapper enforcement', () => {
    const paths = fixture();
    writeFileSync(paths.configFile, JSON.stringify({ autopilot: { zero_paid_spend: true } }));
    writeFileSync(paths.wrapperFile, generatedWrapper('if false; then\n', 'fi\n'));

    const status = inspectZeroPaidSpendStatus({}, paths);
    expect(status.wrapper_declaration).toBe('noncanonical');
    expect(status.configuration_consistent).toBe(false);
  });

  test('does not mistake an export inside an uncalled function for active wrapper enforcement', () => {
    const paths = fixture();
    writeFileSync(paths.configFile, JSON.stringify({ autopilot: { zero_paid_spend: true } }));
    writeFileSync(paths.wrapperFile, generatedWrapper('never_called() {\n', '}\n'));

    const status = inspectZeroPaidSpendStatus({}, paths);
    expect(status.wrapper_declaration).toBe('noncanonical');
    expect(status.configuration_consistent).toBe(false);
  });

  test('does not mistake a command-substitution export for active wrapper enforcement', () => {
    const paths = fixture();
    writeFileSync(paths.configFile, JSON.stringify({ autopilot: { zero_paid_spend: true } }));
    writeFileSync(paths.wrapperFile, generatedWrapper(': "$(\n', ')"\n'));

    const status = inspectZeroPaidSpendStatus({}, paths);
    expect(status.wrapper_declaration).toBe('noncanonical');
    expect(status.configuration_consistent).toBe(false);
  });

  test('does not present a canonical declaration as runtime evidence', () => {
    const paths = fixture();
    writeFileSync(paths.configFile, JSON.stringify({ autopilot: { zero_paid_spend: true } }));
    writeFileSync(paths.wrapperFile, generatedWrapper('', 'unset GBRAIN_QUEUE_ZERO_PAID_SPEND\n'));

    const declaration = inspectZeroPaidSpendStatus({}, paths);
    expect(declaration.wrapper_declaration).toBe('declares_on');
    expect(declaration.configuration_consistent).toBe(true);
    expect(supervisorZeroPaidSpendStatus([], null, 'default').live_supervisor).toBeNull();
  });

  test('reports unreadable config instead of guessing off', () => {
    const paths = fixture();
    writeFileSync(paths.configFile, '{not-json');

    const status = inspectZeroPaidSpendStatus({}, paths);
    expect(status.durable_autopilot).toBe('unreadable');
    expect(status.configuration_consistent).toBe(false);
  });

  test('reports a non-boolean durable choice as invalid and inconsistent', () => {
    const paths = fixture();
    writeFileSync(paths.configFile, JSON.stringify({ autopilot: { zero_paid_spend: 'true' } }));

    const status = inspectZeroPaidSpendStatus({}, paths);
    expect(status.durable_autopilot).toBe('invalid');
    expect(status.configuration_consistent).toBe(false);
  });

  test('surfaces an unrecognized env value while confirming fail-closed enforcement', () => {
    const paths = fixture();
    const status = inspectZeroPaidSpendStatus(
      { GBRAIN_QUEUE_ZERO_PAID_SPEND: 'tru' },
      paths,
    );
    expect(status.current_process).toBe('on');
    expect(status.current_process_value_ambiguous).toBe(true);
  });

  test('keeps live supervisor evidence distinct from durable configuration', async () => {
    const paths = fixture();
    await withEnv({ GBRAIN_HOME: paths.root }, async () => {
      const gbrainDir = join(paths.root, '.gbrain');
      mkdirSync(gbrainDir);
      writeFileSync(join(gbrainDir, 'config.json'), JSON.stringify({ autopilot: { zero_paid_spend: true } }));
      writeFileSync(join(gbrainDir, 'autopilot-run.sh'), generatedWrapper());
      const status = supervisorZeroPaidSpendStatus([
        { event: 'started', supervisor_pid: 7, queue: 'default', lock_acquisition_token: 'old', zero_paid_spend: true },
        { event: 'started', supervisor_pid: 8, queue: 'other', lock_acquisition_token: 'current', zero_paid_spend: true },
        { event: 'started', supervisor_pid: 8, queue: 'default', lock_acquisition_token: 'current', zero_paid_spend: false },
      ], { holder_pid: 8, holder_host: hostname(), acquisition_token: 'current' }, 'default');
      expect(status.live_supervisor).toBe(false);
      expect(status.durable_autopilot).toBe('on');
      expect(formatSupervisorZeroPaidSpendStatus(status)).toContain('live=off durable=on wrapper=declares_on');
    });
  });

  test('does not borrow live evidence from a stale or remotely detected supervisor', () => {
    const events = [
      { event: 'started', supervisor_pid: 7, queue: 'default', lock_acquisition_token: 'old', zero_paid_spend: true },
    ];
    expect(supervisorZeroPaidSpendStatus(events, { holder_pid: 8, holder_host: hostname(), acquisition_token: 'old' }, 'default').live_supervisor).toBeNull();
    expect(supervisorZeroPaidSpendStatus(events, null, 'default').live_supervisor).toBeNull();
    expect(supervisorZeroPaidSpendStatus(events, { holder_pid: 7, holder_host: 'remote-host', acquisition_token: 'old' }, 'default').live_supervisor).toBeNull();
    expect(supervisorZeroPaidSpendStatus(events, { holder_pid: 7, holder_host: hostname(), acquisition_token: 'new' }, 'default').live_supervisor).toBeNull();
  });

  test('doctor warns on an unreadable durable choice instead of guessing', async () => {
    const paths = fixture();
    await withEnv({ GBRAIN_HOME: paths.root }, async () => {
      const gbrainDir = join(paths.root, '.gbrain');
      mkdirSync(gbrainDir);
      writeFileSync(join(gbrainDir, 'config.json'), '{not-json');
      const check = buildZeroPaidSpendDoctorCheck();
      expect(check.status).toBe('warn');
      expect(check.message).toContain('durable_autopilot=unreadable');
      expect(check.details.configuration_consistent).toBe(false);
    });
  });
});
